apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
spec:
  type: NodePort
  selector:
    app: mlflow-serving
  ports:
    - protocol: TCP
      port: 30051  # Cổng bên ngoài
      targetPort: 8080  # Cổng trong container
      nodePort: 30051  # Cổng cố định trên Node
