apiVersion: v1
kind: Service
metadata:
  name: airflow-web-nodeport
  namespace: airflow
spec:
  type: NodePort
  selector:
    component: webserver
  ports:
    - name: web
      port: 8080
      targetPort: 8080
      nodePort: 30080
      