apiVersion: v1
kind: Service
metadata:
  name: flink-web-ui
  namespace: flink
  labels:
    type: flink-jobmanager-ui
spec:
  type: NodePort
  selector:
    app: kafka-to-kafka
    component: jobmanager
  ports:
    - name: rest
      port: 8081
      targetPort: 8081
      nodePort: 31234
