apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport
  namespace: feast
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30432  # Tùy chọn, nên nằm trong khoảng 30000–32767
