apiVersion: v1
kind: Service
metadata:
  name: datahub-web-nodeport
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: datahub-frontend
  ports:
    - name: http
      port: 9002
      targetPort: 9002
      nodePort: 30002
