# datahub-hive-cronjob.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ingest-hive-datahub
  namespace: datahub
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: datahub-ingest
              image: acryldata/datahub-ingestion:latest
              command:
                - /bin/sh
                - -c
                - |
                  python3 -c 'import os; print(open("/config/hive-delta-template.yaml").read().replace("$DATAHUB_TOKEN", os.environ["DATAHUB_TOKEN"]))' > /tmp/hive-delta.yaml
                  datahub ingest -c /tmp/hive-delta.yaml
              env:
                - name: DATAHUB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: datahub-token-secret
                      key: DATAHUB_TOKEN
              volumeMounts:
                - name: config
                  mountPath: /config
          restartPolicy: OnFailure
          volumes:
            - name: config
              configMap:
                name: hive-delta-config
