apiVersion: v1
kind: Service
metadata:
  name: spark-ui-cdc-merchant
  namespace: spark-operator
  labels:
    spark-role: driver
    spark-app-selector: kafka_to_delta_transaction
spec:
  type: NodePort
  selector:
    spark-role: driver
    spark-app-selector: kafka_to_delta_transaction
  ports:
    - name: web-ui
      port: 4040
      targetPort: 4040
      protocol: TCP
      nodePort: 30442
