project: fraud_detection

registry:
  path: s3://feast-feature-registry/registry.db
  s3:
    region_name: us-east-1
    endpoint_url: https://s3.us-east-1.amazonaws.com

provider: local

online_store:
  type: redis
  connection_string: redis://:redis@redis-master.feature-store.svc.cluster.local:6379

offline_store:
  type: feast_trino.trino.TrinoOfflineStore
  host: trino.trino.svc.cluster.local
  port: 8080
  catalog: delta_lake
  connector:
    schema: memory
