apiVersion: v1
kind: Service
metadata:
  name: minio-console-nodeport
  namespace: minio
  labels:
    v1.min.io/console: myminio-console
spec:
  type: NodePort
  selector:
    v1.min.io/tenant: myminio
  ports:
    - name: https-console
      port: 9443
      targetPort: 9443
      nodePort: 30943
