apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: kafka-to-minio-job
  namespace: flink
spec:
  image: huusy/flink:1.16
  imagePullPolicy: Always
  flinkVersion: v1_16
  serviceAccount: flink
  jobManager:
    resource:
      memory: "2048m"
      cpu: 1
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1
  job:
    parallelism: 2
    args: ["-pyclientexec", "/usr/local/bin/python3", "-py", "s3a://share/flink/repo/job_kafka_to_minio.py"]
    entryClass: org.apache.flink.client.python.PythonDriver
    upgradeMode: stateless
  podTemplate:
    spec:
      containers:
        - name: flink-main-container
          volumeMounts:
            - name: kafka-truststore
              mountPath: /opt/flink/secrets
      volumes:
        - name: kafka-truststore
          secret:
            secretName: kafka-jks
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "1"
    s3.access.key: minio
    s3.secret.key: minio123
    s3.endpoint: https://minio.minio.svc.cluster.local:443
    fs.s3a.endpoint: https://minio.minio.svc.cluster.local:443
    fs.s3a.access.key: minio
    fs.s3a.secret.key: minio123
    fs.s3a.path.style.access: "true"
    fs.s3a.connection.ssl.enabled: "true"
    state.backend: filesystem
    state.checkpoints.dir: s3a://raw-zone/checkpoints/
    state.savepoints.dir: s3a://raw-zone/savepoints/
