- name: Update apt cache
  environment:
    DEBIAN_FRONTEND: noninteractive
  apt:
    update_cache: yes
    cache_valid_time: 7200

- name: Install nfs-common
  apt:
    name: nfs-common
    state: present
  when: ansible_os_family == "Debian"
