apiVersion: v1
kind: Service
metadata:
  name: kafka-connect-nodeport
  namespace: kafka
spec:
  type: NodePort
  selector:
    app: cp-kafka-connect
    release: kafka-connect
  ports:
    - name: http
      port: 8083
      targetPort: 8083
      nodePort: 30083
