apiVersion: v1
kind: Secret
metadata:
  name: feast-data-stores
  namespace: feast
stringData:
  # Redis config (used directly by Feast)
  redis: |
    connection_string: redis.feast.svc.cluster.local:6379

  # PostgreSQL config (used by registry)
  sql: |
    path: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres.feast.svc.cluster.local:5432/${POSTGRES_DB}
    cache_ttl_seconds: 60
    sqlalchemy_config_kwargs:
        echo: false
        pool_pre_ping: true

  # MinIO / S3 config (used via env vars)
  AWS_ACCESS_KEY_ID: minio
  AWS_SECRET_ACCESS_KEY: minio123
  S3_ENDPOINT_URL: https://minio.minio.svc.cluster.local:443
  S3_BUCKET: gold-zone
#  AWS_REGION: us-east-1
---
apiVersion: feast.dev/v1alpha1
kind: FeatureStore
metadata:
  name: fraud-detection
  namespace: feast
spec:
  feastProject: fraud_detection
  feastProjectDir:
    git:
      url: https://github.com/vuhuusy/data-lakehouse-platform
      ref: main
  services:
    offlineStore:
      persistence:
        file:
          type: file
    onlineStore:
      persistence:
        store:
          type: redis
          secretRef:
            name: feast-data-stores
      server:
        envFrom:
        - secretRef:
            name: postgres-secret
        - secretRef:
            name: feast-data-stores
        env:
        - name: MPLCONFIGDIR
          value: /tmp
        resources:
          requests:
            cpu: 500m
            memory: 1024Mi
    registry:
      local:
        persistence:
          store:
            type: sql
            secretRef:
              name: feast-data-stores
