apiVersion: v1
kind: Service
metadata:
  name: trino-ui-nodeport
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: trino
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30081