apiVersion: batch/v1
kind: Job
metadata:
  name: feast-materialize-job
  namespace: feast
spec:
  template:
    spec:
      containers:
      - name: feast
        image: huusy/feast:0.16.1
        command: ["bash", "-c"]
        args:
          - |
            feast apply && feast materialize-incremental "$(date +%F)T23:59:59"
        env:
        - name: FEAST_USAGE
          value: "False"
        workingDir: /app
      restartPolicy: Never
