- name: "Setup all nodes: Update, Install Java, Disable Swap"
  hosts: all
  become: yes
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Upgrade system packages
      apt:
        upgrade: dist
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Install Java 11
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Turn off swap immediately
      command: swapoff -a

    - name: Disable swap in /etc/fstab
      replace:
        path: /etc/fstab
        regexp: '^([^#].*swap.*)$'
        replace: '# \1'
